name: Docker

on:
    push:
        branches: [ develop ]

jobs:
    build-and-push-docker-image:
        name: Build Docker image and push to Docker hub
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Set up Docker Buildx
                id: buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build image and push to Docker Hub
                uses: docker/build-push-action@v2
                with:
                    context: ./
                    tags: |
                        zeropingheroes/lanager:develop
                    push: ${{ github.ref == 'refs/heads/develop' }}

            -   name: Image digest
                run: echo ${{ steps.docker_build.outputs.digest }}
