name: Laravel Dusk

on:
    push:
        branches: [ develop ]
        paths:
            - '**.php'
            - '**.json'
            - '**.lock'
jobs:
    behat:
        name: Test with Laravel Dusk
        runs-on: ubuntu-latest
        env:
            APP_KEY: ${{ secrets.APP_KEY }}
            APP_URL: http://localhost:8000
            APP_ENV: testing
            APP_TIMEZONE: UTC
            APP_LOCALE: en
            APP_DEBUG: true
            STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
            GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
            DB_CONNECTION: mysql
            DB_HOST: localhost
            DB_PORT: 3306
            DB_DATABASE: lanager
            DB_USERNAME: root
            DB_PASSWORD: root
            CACHE_DRIVER: file
            SESSION_DRIVER: database
            SESSION_LIFETIME: 7200
            LOG_CHANNEL: file
            DUSK_DRIVER_URL: http://localhost:4444/wd/hub

        steps:
            -   name: Start MySQL
                run: sudo /etc/init.d/mysql start

            -   name: Create database
                run: mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }}

            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'
                    extensions: xmlwriter, zip, pdo, pdo_mysql, tokenizer, simplexml, bcmath, fileinfo

            -   name: Install Composer dependencies
                run: composer install --prefer-dist --no-scripts --no-interaction

            -   name: Link Laravel storage directory
                run: php artisan storage:link

            -   name: Run database migrations
                run: php artisan migrate

            -   name: Seed database
                run: php artisan db:seed --class="Database\\Seeders\\DatabaseSeeder"

            -   name: Upgrade Chrome Driver
                run: php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`

            -   name: Start Chrome Driver
                run: ./vendor/laravel/dusk/bin/chromedriver-linux &

            -   name: Start built-in webserver
                run: php artisan serve > /dev/null 2>&1 &

            -   name: Run Laravel Dusk tests
                run: php artisan dusk

            -   name: Upload Screenshots
                if: failure()
                uses: actions/upload-artifact@v2
                with:
                    name: screenshots
                    path: storage/logs/dusk/screenshots

            -   name: Upload Console Logs
                if: failure()
                uses: actions/upload-artifact@v2
                with:
                    name: console
                    path: storage/logs/dusk/console
